-- 0017(카운터 잠금) 이후 시드된 여행 공유에 좋아요/날짜 다양성 복원 (전 도시).
-- 시드(node scripts/seed-notes.js)가 전부 끝난 뒤 SQL Editor에서 실행. 재실행 안전(멱등).

begin;
update public.city_notes set like_count=42, created_at=now()-interval '2 days', updated_at=now()-interval '2 days' where region_id='krc-부산' and body='광안리 밤바다 보면서 맥주 한 캔. 다리 조명 쇼는 매시 정각에 잠깐 해요.';
update public.city_notes set like_count=38, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='krc-부산' and body='서면 돼지국밥 골목 — 새벽까지 하는 집 많아요. 수육백반에 정구지 듬뿍.';
update public.city_notes set like_count=35, created_at=now()-interval '1 days', updated_at=now()-interval '1 days' where region_id='krc-부산' and body='감천문화마을은 오전 일찍 가면 한산해요. 어린왕자 포토존은 줄이 길어요.';
update public.city_notes set like_count=31, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='krc-부산' and body='해운대보다 송정 해변이 한적해요. 서핑 강습도 여기서 받았어요.';
update public.city_notes set like_count=29, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-부산' and body='자갈치시장 1층에서 회 떠서 2층 초장집으로. 곰장어 꼭 드세요.';
update public.city_notes set like_count=27, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='krc-부산' and body='전포 카페거리 골목이 예뻐요. 작은 로스터리들이 진짜예요.';
update public.city_notes set like_count=24, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='krc-부산' and body='영도 흰여울문화마을 절벽길 뷰가 좋아요. 영화 많이 찍은 곳.';
update public.city_notes set like_count=22, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='krc-부산' and body='여름엔 밀면이죠. 가야밀면 줄 서요. 비빔도 물도 다 괜찮아요.';
update public.city_notes set like_count=20, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='krc-부산' and body='황령산 봉수대 야경 강추. 차 있으면 밤에 올라가세요. 부산 전체가 보여요.';
update public.city_notes set like_count=12, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='krc-부산' and body='태종대 다누비 열차 타고 한 바퀴. 등대랑 절벽 뷰가 시원해요.';
update public.city_notes set like_count=6, created_at=now()-interval '40 days', updated_at=now()-interval '40 days' where region_id='krc-부산' and body='보수동 책방골목 — 헌책 냄새 좋아하면 한 시간은 순삭이에요.';
update public.city_notes set like_count=5, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='krc-부산' and body='다대포 일몰과 꿈의낙조분수. 여름밤 분수쇼 볼만해요.';
update public.city_notes set like_count=40, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-서울' and body='북촌 한옥마을은 평일 오전이 조용해요. 주민 사는 곳이라 조용히 다녀요.';
update public.city_notes set like_count=34, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='krc-서울' and body='을지로 노가리 골목 — 저녁 6시 넘으면 야외 테이블 꽉 차요.';
update public.city_notes set like_count=28, created_at=now()-interval '10 days', updated_at=now()-interval '10 days' where region_id='krc-서울' and body='성수동 연무장길 카페·편집숍 많아요. 대림창고 근처부터 걸어보세요.';
update public.city_notes set like_count=25, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='krc-서울' and body='남산타워는 케이블카보다 걸어 올라가는 길이 예뻐요. 야경 좋아요.';
update public.city_notes set like_count=19, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='krc-서울' and body='광장시장 빈대떡·마약김밥. 평일 낮에 가야 자리 있어요.';
update public.city_notes set like_count=15, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='krc-서울' and body='뚝섬한강공원에서 러닝하고 편의점 라면. 이게 서울 감성이에요.';
update public.city_notes set like_count=11, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='krc-서울' and body='서촌 골목 서점이랑 작은 갤러리들. 경복궁 서쪽이라 조용해요.';
update public.city_notes set like_count=33, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='krc-제주시' and body='사려니숲길 아침 산책 강추. 안개 낀 날이 더 좋아요.';
update public.city_notes set like_count=26, created_at=now()-interval '9 days', updated_at=now()-interval '9 days' where region_id='krc-제주시' and body='흑돼지는 관광지보다 동네 고깃집이 나아요. 멜젓에 찍어서.';
update public.city_notes set like_count=21, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='krc-제주시' and body='한라산 성판악 코스는 새벽 출발 필수. 정상 대피소에서 컵라면.';
update public.city_notes set like_count=17, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='krc-제주시' and body='협재 해수욕장 물색이 진짜 에메랄드. 오후 늦게 사람 빠져요.';
update public.city_notes set like_count=9, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='krc-제주시' and body='애월 해안도로 카페들. 뷰값이라도 한 번은 가볼 만해요.';
update public.city_notes set like_count=31, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-경주시' and body='첨성대·대릉원 야간 조명 예뻐요. 자전거 빌려서 도는 게 최고.';
update public.city_notes set like_count=24, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='krc-경주시' and body='불국사는 이른 아침에. 석굴암까지 걸어 올라가면 한 시간쯤.';
update public.city_notes set like_count=18, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='krc-경주시' and body='황리단길 한옥 카페들. 주말엔 사람 많으니 평일 추천.';
update public.city_notes set like_count=12, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='krc-경주시' and body='보문호수 벚꽃길 산책. 봄에 오면 진짜 미쳐요.';
update public.city_notes set like_count=7, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='krc-경주시' and body='경주빵보다 찰보리빵이 더 맛있어요. 개인 취향이지만요.';
update public.city_notes set like_count=29, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='krc-전주시' and body='한옥마을은 아침 8시가 제일 좋아요. 낮엔 사람 반, 상점 반.';
update public.city_notes set like_count=23, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='krc-전주시' and body='진짜 콩나물국밥은 남부시장 쪽. 수란 풀어서 먹는 게 정석.';
update public.city_notes set like_count=16, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='krc-전주시' and body='전동성당 앞 야경 예뻐요. 한복 대여점 근처라 사람 많지만요.';
update public.city_notes set like_count=10, created_at=now()-interval '25 days', updated_at=now()-interval '25 days' where region_id='krc-전주시' and body='가맥집 문화 재밌어요. 슈퍼에서 맥주 사서 황태구이랑.';
update public.city_notes set like_count=30, created_at=now()-interval '2 days', updated_at=now()-interval '2 days' where region_id='krc-강릉시' and body='안목해변 커피거리 — 바다 보면서 마시는 커피가 왜 이렇게 맛있죠.';
update public.city_notes set like_count=22, created_at=now()-interval '9 days', updated_at=now()-interval '9 days' where region_id='krc-강릉시' and body='경포대 일출 보려면 새벽 5시. 겨울엔 사람도 적고 공기 맑아요.';
update public.city_notes set like_count=17, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='krc-강릉시' and body='초당 순두부 마을. 짬뽕순두부 파는 집이 웨이팅 길어요.';
update public.city_notes set like_count=11, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='krc-강릉시' and body='정동진 바다부채길 트레킹. 절벽 따라 걷는 길이 시원해요.';
update public.city_notes set like_count=28, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='krc-여수시' and body='여수 밤바다는 진짜예요. 돌산대교 조명 켜지면 노래가 절로 나와요.';
update public.city_notes set like_count=20, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='krc-여수시' and body='게장백반 정식 — 간장게장 무한리필 하는 집들 많아요.';
update public.city_notes set like_count=14, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='krc-여수시' and body='해상케이블카 크리스탈 캐빈 타보세요. 바닥이 유리라 아찔해요.';
update public.city_notes set like_count=8, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='krc-여수시' and body='오동도 동백꽃은 2~3월. 방파제 걸어서 들어가요.';
update public.city_notes set like_count=26, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='krc-속초시' and body='속초중앙시장 닭강정 — 줄 서더라도 갓 튀긴 거 드세요.';
update public.city_notes set like_count=19, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='krc-속초시' and body='설악산 울산바위 코스는 계단 지옥이지만 정상 뷰가 보상해줘요.';
update public.city_notes set like_count=12, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='krc-속초시' and body='아바이마을 갯배 타보세요. 손으로 줄 당겨서 건너는 거 재밌어요.';
update public.city_notes set like_count=6, created_at=now()-interval '33 days', updated_at=now()-interval '33 days' where region_id='krc-속초시' and body='영금정 일출 명소. 바다 바로 앞이라 파도 소리가 좋아요.';
update public.city_notes set like_count=25, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='krc-통영시' and body='동피랑 벽화마을 — 골목 좁으니 조용히 다녀요. 주민 사는 곳이에요.';
update public.city_notes set like_count=18, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='krc-통영시' and body='통영 충무김밥은 시장 안 노포가 진짜. 어묵이랑 무김치 조합.';
update public.city_notes set like_count=11, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='krc-통영시' and body='한산도 가는 배 타고 이순신 유적지. 뱃길 자체가 여행이에요.';
update public.city_notes set like_count=7, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='krc-통영시' and body='미륵산 케이블카 타면 다도해가 쫙 펼쳐져요. 날 맑을 때 가세요.';
update public.city_notes set like_count=28, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-서귀포시' and body='성산일출봉은 서귀포예요! 오전 일찍 올라야 덜 덥고 사람도 적어요.';
update public.city_notes set like_count=19, created_at=now()-interval '10 days', updated_at=now()-interval '10 days' where region_id='krc-서귀포시' and body='중문 색달해변 — 서핑 성지. 그냥 보기만 해도 물색이 달라요.';
update public.city_notes set like_count=13, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='krc-서귀포시' and body='서귀포 매일올레시장에서 마농치킨이랑 오메기떡 포장해서 숙소에서.';
update public.city_notes set like_count=8, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='krc-서귀포시' and body='쇠소깍 투명카약 — 민물과 바다가 만나는 곳이라 물색이 독특해요.';
update public.city_notes set like_count=27, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-인천' and body='차이나타운 짜장면박물관 보고 송월동 동화마을로 이어 걸으면 반나절 코스예요.';
update public.city_notes set like_count=21, created_at=now()-interval '9 days', updated_at=now()-interval '9 days' where region_id='krc-인천' and body='월미도 디스코팡팡… 어른도 재밌어요. 바이킹은 바다 보면서 타요.';
update public.city_notes set like_count=15, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='krc-인천' and body='송도 센트럴파크 야경 산책. 수상택시도 타볼 만해요.';
update public.city_notes set like_count=8, created_at=now()-interval '25 days', updated_at=now()-interval '25 days' where region_id='krc-인천' and body='소래포구 새우튀김이랑 젓갈. 어시장 구경만 해도 재밌어요.';
update public.city_notes set like_count=25, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='krc-대구' and body='서문시장 야시장 — 납작만두랑 막창은 여기서. 저녁 7시쯤 제일 활기차요.';
update public.city_notes set like_count=19, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='krc-대구' and body='김광석 다시그리기 길 — 벽화 보면서 천천히. 주말엔 버스킹도 해요.';
update public.city_notes set like_count=12, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='krc-대구' and body='근대문화골목 투어 추천. 계산성당·이상화 고택 쪽이 예뻐요.';
update public.city_notes set like_count=7, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='krc-대구' and body='동성로 카페 골목은 밤늦게까지 열어요. 대구 커피 수준 높아요.';
update public.city_notes set like_count=30, created_at=now()-interval '2 days', updated_at=now()-interval '2 days' where region_id='krc-대전' and body='성심당은 본점만 진리. 튀김소보로는 갓 나온 오전 시간대 노리세요.';
update public.city_notes set like_count=14, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='krc-대전' and body='대청호 오백리길 드라이브 — 벚꽃철엔 호수길이 장관이에요.';
update public.city_notes set like_count=10, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='krc-대전' and body='유성온천 족욕장은 무료예요. 여행 중 다리 풀기 좋아요.';
update public.city_notes set like_count=6, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='krc-대전' and body='엑스포다리 야경이랑 한밭수목원 산책 묶어서 저녁 코스로.';
update public.city_notes set like_count=26, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='krc-수원시' and body='수원화성 성곽길 한 바퀴 — 화서문에서 시작해서 방화수류정이 하이라이트.';
update public.city_notes set like_count=18, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='krc-수원시' and body='행궁동 골목 카페들 요즘 핫해요. 벽화골목이랑 같이 돌아요.';
update public.city_notes set like_count=13, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='krc-수원시' and body='통닭거리 왕갈비통닭 — 두 명이 한 마리면 충분해요.';
update public.city_notes set like_count=7, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='krc-수원시' and body='플라잉수원 열기구에서 화성 전경이 다 보여요. 바람 약한 날만 떠요.';
update public.city_notes set like_count=24, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='krc-춘천시' and body='명동 닭갈비 골목 — 철판에 볶다가 마지막 볶음밥까지가 국룰이에요.';
update public.city_notes set like_count=16, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='krc-춘천시' and body='소양강 스카이워크 + 소양강처녀상. 아침엔 물안개가 예술이에요.';
update public.city_notes set like_count=12, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='krc-춘천시' and body='남이섬은 춘천이에요! 배 타고 5분. 메타세쿼이아길은 오전이 한산해요.';
update public.city_notes set like_count=6, created_at=now()-interval '32 days', updated_at=now()-interval '32 days' where region_id='krc-춘천시' and body='김유정역 레일바이크 — 연인이든 가족이든 다 좋아해요. 예약 필수.';
update public.city_notes set like_count=23, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='krc-안동시' and body='하회마을은 셔틀 타고 들어가요. 부용대 올라가서 내려다보는 뷰가 최고.';
update public.city_notes set like_count=17, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='krc-안동시' and body='월영교 야경 — 달 뜨는 밤이 진짜예요. 문보트도 탈 수 있어요.';
update public.city_notes set like_count=11, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='krc-안동시' and body='구시장 찜닭골목에서 안동찜닭 원조 맛. 양 많으니 둘 이상 가세요.';
update public.city_notes set like_count=5, created_at=now()-interval '34 days', updated_at=now()-interval '34 days' where region_id='krc-안동시' and body='병산서원 만대루에서 보는 낙동강 — 고요함 그 자체예요.';
update public.city_notes set like_count=25, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='krc-군산시' and body='이성당 단팥빵·야채빵 — 아침 일찍 가야 줄이 짧아요. 전국에서 제일 오래된 빵집.';
update public.city_notes set like_count=15, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='krc-군산시' and body='경암동 철길마을에서 교복 빌려 입고 사진 찍는 코스. 오후 빛이 예뻐요.';
update public.city_notes set like_count=10, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='krc-군산시' and body='초원사진관(8월의 크리스마스 촬영지) 근처 시간여행마을은 다 걸어서 돼요.';
update public.city_notes set like_count=6, created_at=now()-interval '33 days', updated_at=now()-interval '33 days' where region_id='krc-군산시' and body='군산은 짬뽕 성지예요. 물짜장도 군산이 원조라는 설이 있어요.';
update public.city_notes set like_count=22, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='krc-목포시' and body='목포해상케이블카 — 유달산에서 고하도까지. 크리스탈 캐빈 추천.';
update public.city_notes set like_count=14, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='krc-목포시' and body='근대역사관 거리 자체가 영화 세트장 같아요. 밤에 조명 켜지면 분위기 좋아요.';
update public.city_notes set like_count=9, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='krc-목포시' and body='민어의 거리에서 민어회 코스. 여름 보양식으론 이만한 게 없어요.';
update public.city_notes set like_count=5, created_at=now()-interval '35 days', updated_at=now()-interval '35 days' where region_id='krc-목포시' and body='갓바위는 해질녘에. 바다 위 데크길 따라 걷다 보면 노을이 집니다.';
update public.city_notes set like_count=24, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='krc-포항시' and body='환호공원 스페이스워크 — 해질녘에 올라가면 야경까지 다 봐요. 무료예요.';
update public.city_notes set like_count=16, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='krc-포항시' and body='죽도시장 과메기(겨울)랑 물회(여름). 대게도 생각보다 저렴해요.';
update public.city_notes set like_count=11, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='krc-포항시' and body='호미곶 상생의 손 일출 — 새해엔 미어터지니 평일 새벽 추천.';
update public.city_notes set like_count=6, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='krc-포항시' and body='영일대 해수욕장 밤 산책. 해상누각에서 보는 야경이 좋아요.';
update public.city_notes set like_count=23, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='krc-거제시' and body='바람의 언덕 — 도장포 마을에서 올라가요. 풍차랑 바다 조합이 이국적이에요.';
update public.city_notes set like_count=17, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='krc-거제시' and body='외도 보타니아는 유람선으로만 가요. 해금강 코스랑 묶으면 알차요.';
update public.city_notes set like_count=10, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='krc-거제시' and body='학동 몽돌해변 — 파도가 돌 굴리는 소리가 ASMR이에요.';
update public.city_notes set like_count=7, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='krc-거제시' and body='매미성 — 개인이 쌓은 성인데 규모가 어마어마해요. 사진 명소.';
update public.city_notes set like_count=45, created_at=now()-interval '2 days', updated_at=now()-interval '2 days' where region_id='jpc-tokyo' and body='시부야 스크램블은 스타벅스 2층에서 보는 게 제일 잘 보여요.';
update public.city_notes set like_count=37, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-tokyo' and body='신주쿠 골든가이 근처 라멘집들. 자판기로 주문하는 곳이 대부분이에요.';
update public.city_notes set like_count=30, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='jpc-tokyo' and body='센소지는 아침 7시에 가면 사람 거의 없어요. 나카미세 상점가는 9시부터.';
update public.city_notes set like_count=23, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='jpc-tokyo' and body='시모키타자와 빈티지숍 골목. 하루 종일 돌아도 안 지겨워요.';
update public.city_notes set like_count=18, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='jpc-tokyo' and body='츠키지 장외시장 아침 식사. 계란말이랑 참치덮밥 줄 서요.';
update public.city_notes set like_count=10, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='jpc-tokyo' and body='야나카 긴자 상점가 — 옛 도쿄 분위기. 고양이 많아요.';
update public.city_notes set like_count=39, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='jpc-osaka' and body='도톤보리 글리코 간판 앞은 항상 사람 많아요. 밤에 조명 켜지면 예뻐요.';
update public.city_notes set like_count=32, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='jpc-osaka' and body='타코야키는 체인보다 골목 노점이 나아요. 갓 구운 거 뜨거우니 조심.';
update public.city_notes set like_count=22, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='jpc-osaka' and body='오사카성 천수각보다 주변 공원이 좋아요. 벚꽃 시즌엔 인산인해.';
update public.city_notes set like_count=16, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='jpc-osaka' and body='쿠로몬시장에서 해산물 구이. 그 자리에서 먹을 수 있어요.';
update public.city_notes set like_count=8, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='jpc-osaka' and body='신세카이 츠텐카쿠 주변 쿠시카츠 골목. 소스 두 번 찍기 금지예요.';
update public.city_notes set like_count=44, created_at=now()-interval '1 days', updated_at=now()-interval '1 days' where region_id='jpc-kyoto' and body='후시미이나리 천 개의 토리이 — 새벽 6시 가면 아무도 없어요. 강추.';
update public.city_notes set like_count=36, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-kyoto' and body='아라시야마 대나무숲은 오전 8시 전에. 늦으면 사진 못 찍어요.';
update public.city_notes set like_count=27, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-kyoto' and body='기온 하나미코지 저녁 산책. 게이코 사진 촬영은 금지라 조심하세요.';
update public.city_notes set like_count=19, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='jpc-kyoto' and body='철학의 길 벚꽃 시즌 최고. 은각사까지 천천히 걸어보세요.';
update public.city_notes set like_count=13, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='jpc-kyoto' and body='니시키시장 먹거리 골목. 두유 도넛이랑 절임 반찬 맛있어요.';
update public.city_notes set like_count=34, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='jpc-fukuoka' and body='나카스 포장마차(야타이)는 저녁 6시부터. 라멘이랑 명란 계란말이.';
update public.city_notes set like_count=27, created_at=now()-interval '10 days', updated_at=now()-interval '10 days' where region_id='jpc-fukuoka' and body='이치란 본점보다 동네 돈코츠 라멘집이 더 진해요. 카에다마 꼭.';
update public.city_notes set like_count=20, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='jpc-fukuoka' and body='다자이후 텐만구는 전철로 30분. 매화 시즌이 예뻐요.';
update public.city_notes set like_count=13, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='jpc-fukuoka' and body='오호리 공원 산책 + 후쿠오카성터. 현지인 조깅 코스예요.';
update public.city_notes set like_count=8, created_at=now()-interval '32 days', updated_at=now()-interval '32 days' where region_id='jpc-fukuoka' and body='모모치 해변 노을. 후쿠오카 타워랑 같이 보면 좋아요.';
update public.city_notes set like_count=33, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-sapporo' and body='스스키노 징기스칸 — 양고기 냄새 걱정했는데 전혀 안 나요.';
update public.city_notes set like_count=26, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-sapporo' and body='오타루 운하까지 전철로 40분. 겨울 눈 쌓인 풍경이 그림이에요.';
update public.city_notes set like_count=19, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='jpc-sapporo' and body='삿포로 맥주 박물관 시음 코스. 갓 뽑은 생맥주 맛이 달라요.';
update public.city_notes set like_count=12, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='jpc-sapporo' and body='니조시장 해산물 덮밥. 성게·연어알 올린 거 강추.';
update public.city_notes set like_count=7, created_at=now()-interval '35 days', updated_at=now()-interval '35 days' where region_id='jpc-sapporo' and body='모이와야마 야경 — 일본 3대 야경이라던데 진짜 예뻐요.';
update public.city_notes set like_count=31, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-naha' and body='마키시 공설시장 1층에서 해산물 사면 2층 식당에서 조리해줘요. 아침에 가야 싱싱해요.';
update public.city_notes set like_count=24, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='jpc-naha' and body='슈리성 성벽 산책로는 무료예요. 복원 공사 과정을 공개하는 것도 볼거리.';
update public.city_notes set like_count=16, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='jpc-naha' and body='츠보야 야치문(도자기) 거리 — 국제거리에서 걸어서 10분인데 분위기가 확 조용해져요.';
update public.city_notes set like_count=10, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='jpc-naha' and body='국제거리보다 뒷골목 이자카야가 좋아요. 오키나와 소바 꼭.';
update public.city_notes set like_count=28, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='jpc-nagoya' and body='히츠마부시(장어덮밥) — 세 가지 방식으로 먹는 게 재밌어요.';
update public.city_notes set like_count=18, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='jpc-nagoya' and body='나고야성 천수각은 공사 중일 수 있어요. 혼마루 어전은 볼만해요.';
update public.city_notes set like_count=11, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='jpc-nagoya' and body='오스 상점가 — 전자상가랑 빈티지숍 섞여 있어요. 구경거리 많아요.';
update public.city_notes set like_count=6, created_at=now()-interval '34 days', updated_at=now()-interval '34 days' where region_id='jpc-nagoya' and body='미소카츠는 호불호 갈려요. 저는 좋았는데 짜다는 사람도 많아요.';
update public.city_notes set like_count=26, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='jpc-yokohama' and body='미나토미라이 야경은 오산바시 부두에서 보세요. 대관람차까지 다 보여요.';
update public.city_notes set like_count=18, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='jpc-yokohama' and body='요코하마 중화가 — 일본 최대 차이나타운. 만두 먹으면서 걸어요.';
update public.city_notes set like_count=12, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='jpc-yokohama' and body='아카렌가 창고는 계절 이벤트를 자주 해요. 겨울 크리스마스 마켓이 유명.';
update public.city_notes set like_count=8, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='jpc-yokohama' and body='컵누들 뮤지엄에서 나만의 컵라면 만들기 — 어른이 더 진심이 돼요.';
update public.city_notes set like_count=27, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-kobe' and body='고베규는 런치가 반값이에요. 철판 카운터에서 구워주는 걸 보는 재미.';
update public.city_notes set like_count=17, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='jpc-kobe' and body='기타노 이진칸 — 언덕 위 서양식 저택 거리. 스타벅스 이진칸점도 예뻐요.';
update public.city_notes set like_count=13, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='jpc-kobe' and body='롯코산 야경 — 일본 3대 야경. 케이블카 타고 올라가요.';
update public.city_notes set like_count=7, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='jpc-kobe' and body='하버랜드 모자이크 대관람차 + 메리켄파크 산책을 저녁 코스로.';
update public.city_notes set like_count=29, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='jpc-nara' and body='나라공원 사슴은 인사를 해요(진짜로). 사슴전병은 손에 들고 있으면 달려드니 주의.';
update public.city_notes set like_count=20, created_at=now()-interval '10 days', updated_at=now()-interval '10 days' where region_id='jpc-nara' and body='도다이지 대불 — 사진으로 보던 것보다 훨씬 커요.';
update public.city_notes set like_count=14, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='jpc-nara' and body='나카타니도 요모기모찌 — 고속 떡메치기 보고 갓 만든 거 먹기.';
update public.city_notes set like_count=8, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='jpc-nara' and body='가스가타이샤 참배길의 이끼 낀 석등이 몽환적이에요. 아침 추천.';
update public.city_notes set like_count=25, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-kanazawa' and body='겐로쿠엔 — 일본 3대 정원. 눈 내린 겨울 설경이 제일 유명해요.';
update public.city_notes set like_count=18, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-kanazawa' and body='히가시차야 거리에서 금박 소프트아이스크림 — 가나자와가 일본 금박의 도시래요.';
update public.city_notes set like_count=12, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='jpc-kanazawa' and body='오미초 시장 카이센동 — 아침에 가면 줄 없이 먹어요.';
update public.city_notes set like_count=7, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='jpc-kanazawa' and body='21세기 미술관 수영장 작품은 예약하고 가세요.';
update public.city_notes set like_count=24, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-hiroshima' and body='평화기념공원과 원폭돔 — 자료관은 마음이 무겁지만 꼭 봐야 할 곳이에요.';
update public.city_notes set like_count=19, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='jpc-hiroshima' and body='히로시마 오코노미야키는 면이 들어가요. 오코노미무라엔 한 건물에 가게 20곳.';
update public.city_notes set like_count=15, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='jpc-hiroshima' and body='미야지마(이쓰쿠시마 신사)는 페리로 금방이라 당일로 다녀왔어요. 물때 확인 필수.';
update public.city_notes set like_count=10, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='jpc-hiroshima' and body='히로시마성 천수각에서 시내가 한눈에 보여요.';
update public.city_notes set like_count=26, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='jpc-hakodate' and body='하코다테야마 야경 — 일몰 30분 전에 로프웨이로 올라가 자리 잡으세요.';
update public.city_notes set like_count=18, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-hakodate' and body='하코다테 아침시장 카이센동 — 오징어 낚시 체험도 있어요. 활오징어회가 별미.';
update public.city_notes set like_count=12, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='jpc-hakodate' and body='고료카쿠 타워에서 보는 별 모양 성곽 — 벚꽃철엔 분홍 별이 돼요.';
update public.city_notes set like_count=7, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='jpc-hakodate' and body='베이 에리어 카네모리 붉은 벽돌 창고 — 저녁 산책 코스로 좋아요.';
update public.city_notes set like_count=25, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-otaru' and body='오타루 운하는 해 지고 가스등 켜질 때가 진짜예요. 겨울 눈빛 축제도.';
update public.city_notes set like_count=16, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='jpc-otaru' and body='오르골당 본관 앞 증기시계 — 15분마다 증기를 뿜어요. 기념품은 여기서.';
update public.city_notes set like_count=11, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='jpc-otaru' and body='스시야도리(초밥거리) — 오타루는 초밥 성지예요. 런치 세트가 합리적.';
update public.city_notes set like_count=6, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='jpc-otaru' and body='기타이치 글라스 공방 구경 — 램프 백여 개 켜진 카페가 유명해요.';
update public.city_notes set like_count=27, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='jpc-kamakura' and body='슬램덩크 건널목(가마쿠라코코마에역) — 에노덴 타고 가요. 아침이 역광 없어요.';
update public.city_notes set like_count=22, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-kamakura' and body='가마쿠라 대불(고토쿠인) — 안에도 들어갈 수 있어요.';
update public.city_notes set like_count=13, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='jpc-kamakura' and body='코마치도리 먹거리 골목 — 크로켓 먹으면서 하치만구까지 걸어요.';
update public.city_notes set like_count=8, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='jpc-kamakura' and body='호코쿠지 대나무숲 — 아라시야마보다 한적하고 말차도 마실 수 있어요.';
update public.city_notes set like_count=23, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-nagasaki' and body='이나사야마 야경 — 세계 신 3대 야경으로 뽑혔대요. 로프웨이로 5분.';
update public.city_notes set like_count=17, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-nagasaki' and body='시카이로가 나가사키 짬뽕 원조예요. 카스텔라는 후쿠사야 큐브가 선물용으로 딱.';
update public.city_notes set like_count=11, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='jpc-nagasaki' and body='구라바엔(글로버 가든) — 언덕에서 항구를 내려다보는 뷰. 에스컬레이터 있어요.';
update public.city_notes set like_count=6, created_at=now()-interval '32 days', updated_at=now()-interval '32 days' where region_id='jpc-nagasaki' and body='데지마 — 에도시대 유일한 서양 무역창구. 복원을 잘 해놨어요.';
update public.city_notes set like_count=24, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='jpc-sendai' and body='센다이 규탄(소혀구이) — 두툼하게 구운 게 진짜예요. 어디든 수준급.';
update public.city_notes set like_count=14, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='jpc-sendai' and body='즈이호덴 — 다테 마사무네 묘소. 화려한 장식이 볼만해요.';
update public.city_notes set like_count=9, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='jpc-sendai' and body='아오바성터에서 마사무네 기마상이랑 시내 뷰. 자전거로 돌기 좋아요.';
update public.city_notes set like_count=6, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='jpc-sendai' and body='조젠지도리 느티나무 가로수길 — 12월엔 빛의 페이전트(일루미네이션).';
update public.city_notes set like_count=41, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='thc-bangkok' and body='짜뚜짝 주말시장은 아침 일찍. 오후엔 더워서 못 돌아다녀요.';
update public.city_notes set like_count=34, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='thc-bangkok' and body='왓아룬은 강 건너에서 보는 야경이 더 예뻐요. 배 타고 건너세요.';
update public.city_notes set like_count=26, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='thc-bangkok' and body='카오산로드는 밤에 가야 제맛. 팟타이 노점 저렴해요.';
update public.city_notes set like_count=20, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='thc-bangkok' and body='루프탑 바는 드레스코드 있어요. 반바지·슬리퍼 안 됩니다.';
update public.city_notes set like_count=12, created_at=now()-interval '25 days', updated_at=now()-interval '25 days' where region_id='thc-bangkok' and body='담넌사두억 수상시장은 투어로 가는 게 편해요. 아침 일찍 출발.';
update public.city_notes set like_count=35, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='thc-chiangmai' and body='치앙마이 올드시티는 자전거로 도는 게 좋아요. 사원이 골목마다 있어요.';
update public.city_notes set like_count=29, created_at=now()-interval '9 days', updated_at=now()-interval '9 days' where region_id='thc-chiangmai' and body='도이수텝 사원 — 썽태우 타고 올라가요. 해질녘 뷰가 좋아요.';
update public.city_notes set like_count=23, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='thc-chiangmai' and body='님만해민 카페거리. 노마드들 많아서 와이파이 잘 돼요.';
update public.city_notes set like_count=17, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='thc-chiangmai' and body='일요일 워킹스트리트 야시장. 수공예품 저렴하고 먹거리 많아요.';
update public.city_notes set like_count=11, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='thc-chiangmai' and body='카오소이는 치앙마이가 본고장. 로컬 식당이 진짜 맛있어요.';
update public.city_notes set like_count=30, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='thc-phuket' and body='빠통은 번잡해요. 조용한 거 원하면 까따·까론 해변으로.';
update public.city_notes set like_count=25, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='thc-phuket' and body='피피섬 투어는 스피드보트보다 페리가 덜 흔들려요. 멀미약 챙기세요.';
update public.city_notes set like_count=18, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='thc-phuket' and body='푸켓 올드타운 포르투갈풍 건물들. 일요일엔 워킹스트리트 열려요.';
update public.city_notes set like_count=10, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='thc-phuket' and body='빅부다 전망대에서 섬 전체가 보여요. 오토바이 렌트하면 편해요.';
update public.city_notes set like_count=27, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='thc-pattaya' and body='꼬란섬 당일치기 추천. 방콕에서 가까운데 물은 훨씬 맑아요.';
update public.city_notes set like_count=20, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='thc-pattaya' and body='진리의 성전(Sanctuary of Truth) — 통나무 조각이 압도적이에요.';
update public.city_notes set like_count=13, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='thc-pattaya' and body='워킹스트리트는 호불호 확실해요. 가족 여행이면 패스.';
update public.city_notes set like_count=7, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='thc-pattaya' and body='농눅빌리지 정원 넓어요. 반나절은 잡아야 해요.';
update public.city_notes set like_count=29, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='thc-krabi' and body='라일레이 비치는 배로만 갈 수 있어요. 그래서 더 조용해요.';
update public.city_notes set like_count=21, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='thc-krabi' and body='에메랄드 풀 + 온천 폭포 코스. 물색이 진짜 에메랄드예요.';
update public.city_notes set like_count=15, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='thc-krabi' and body='아오낭에서 4섬 투어. 롱테일보트가 스피드보트보다 운치 있어요.';
update public.city_notes set like_count=9, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='thc-krabi' and body='타이거 케이브 사원 계단 1237개… 올라가면 후회 안 해요.';
update public.city_notes set like_count=26, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='thc-ayutthaya' and body='왓 마하탓 나무뿌리 불상 머리 — 사진 찍을 때 머리보다 낮게 앉아야 해요.';
update public.city_notes set like_count=18, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='thc-ayutthaya' and body='자전거 빌려서 유적 도는 게 최고. 하루면 충분해요.';
update public.city_notes set like_count=11, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='thc-ayutthaya' and body='방콕에서 기차로 1시간 반. 3등석도 나쁘지 않아요.';
update public.city_notes set like_count=6, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='thc-ayutthaya' and body='일몰 때 왓 차이왓타나람이 붉게 물들어요. 강 건너에서 보세요.';
update public.city_notes set like_count=26, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='thc-chiangrai' and body='왓 롱쿤(화이트 템플) — 오전 일찍 가야 단체 관광객을 피해요. 디테일이 미쳤어요.';
update public.city_notes set like_count=18, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='thc-chiangrai' and body='블루 템플 — 파란색과 금색 조합이 강렬해요. 화이트 템플이랑 같이 봐요.';
update public.city_notes set like_count=11, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='thc-chiangrai' and body='싱하 파크 — 차밭에서 자전거 타고 짚라인도. 반나절 코스.';
update public.city_notes set like_count=7, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='thc-chiangrai' and body='토요 워킹스트리트 야시장 먹거리 구경. 시계탑 야간 라이트쇼도 잠깐 볼만해요.';
update public.city_notes set like_count=23, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='thc-huahin' and body='후아힌 야시장 해산물 구이가 방콕 반값이에요. 치카다 마켓은 주말만 열어요.';
update public.city_notes set like_count=15, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='thc-huahin' and body='후아힌 기차역 — 태국에서 제일 예쁜 역이래요. 왕실 대합실이 포인트.';
update public.city_notes set like_count=10, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='thc-huahin' and body='해변에서 말 타기 — 후아힌 명물이에요. 아침 산책 때 흥정하세요.';
update public.city_notes set like_count=6, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='thc-huahin' and body='카오 따끼압(원숭이산) 전망대 — 해변이 쭉 보여요. 원숭이한테 소지품 주의.';
update public.city_notes set like_count=22, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='thc-kosamui' and body='차웽 비치가 메인이지만 라마이가 물이 더 잔잔해요. 취향 차이.';
update public.city_notes set like_count=12, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='thc-kosamui' and body='피셔맨스 빌리지 금요 야시장 — 사무이에서 제일 감성적인 곳이에요.';
update public.city_notes set like_count=15, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='thc-kosamui' and body='빅 부다 사원 — 섬 북쪽. 해질녘 금색으로 물들 때가 예뻐요.';
update public.city_notes set like_count=9, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='thc-kosamui' and body='나무앙 폭포 2단까지 트레킹 — 슬리퍼 말고 운동화 신으세요.';
update public.city_notes set like_count=21, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='thc-kanchanaburi' and body='콰이강의 다리 — 기차가 지나갈 때 다리 위에 있으면 대피 공간으로 비켜요.';
update public.city_notes set like_count=16, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='thc-kanchanaburi' and body='죽음의 철도 기차 탑승 — 탐크라새 절벽 구간이 하이라이트예요.';
update public.city_notes set like_count=13, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='thc-kanchanaburi' and body='에라완 폭포는 시내에서 차로 1시간 반. 7단까지 오르면 에메랄드빛 천연 풀.';
update public.city_notes set like_count=6, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='thc-kanchanaburi' and body='연합군 전쟁묘지 — 조용히 둘러보세요. 태면철도센터 박물관이 바로 옆이에요.';
update public.city_notes set like_count=20, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='thc-sukhothai' and body='수코타이 역사공원은 자전거가 정답이에요. 중심구역만 해도 반나절.';
update public.city_notes set like_count=14, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='thc-sukhothai' and body='왓 시춤 아차나 불상 — 틈새로 보이는 그 유명한 사진이 여기예요.';
update public.city_notes set like_count=10, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='thc-sukhothai' and body='러이끄라통 발상지 — 11월에 오면 역사공원에서 등불 축제를 해요.';
update public.city_notes set like_count=7, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='thc-sukhothai' and body='왓 마하탓 일출 — 연꽃 봉오리 탑 실루엣이 수코타이의 상징이에요.';
update public.city_notes set like_count=18, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='thc-hatyai' and body='킴용 시장 — 말레이시아 물건까지 섞인 국경도시 시장. 견과류·건과일이 싸요.';
update public.city_notes set like_count=14, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='thc-hatyai' and body='핫야이는 딤섬 아침이 국룰이에요. 새벽부터 여는 집이 많아요.';
update public.city_notes set like_count=9, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='thc-hatyai' and body='시립공원 케이블카 — 언덕 위 사원과 시내 뷰. 저녁에 시원해요.';
update public.city_notes set like_count=6, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='thc-hatyai' and body='그린웨이 나이트마켓 — 로컬 젊은이들이 가는 곳. 남부 음식 도전해보세요.';
update public.city_notes set like_count=22, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='thc-pakchong' and body='카오야이 국립공원 입구 도시예요. 헤우나록 폭포까지, 야생 코끼리 만나면 차 안 대기.';
update public.city_notes set like_count=13, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='thc-pakchong' and body='카오야이 와이너리 투어(PB밸리 등) — 태국 와인이 생각보다 괜찮아요.';
update public.city_notes set like_count=10, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='thc-pakchong' and body='프리모 피아자 — 이탈리아 마을 콘셉트 포토스팟. 가족 여행객이 많아요.';
update public.city_notes set like_count=7, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='thc-pakchong' and body='방콕에서 2시간 반이라 주말 드라이브 코스로 최고예요. 아침 공기가 달라요.';
commit;
