-- 0017(카운터 잠금) 이후 시드된 JP/TH 여행 공유에 좋아요/날짜 다양성 복원.
-- 시드 재심기(node scripts/seed-notes.js)가 전부 끝난 뒤 SQL Editor에서 실행.

begin;
update public.city_notes set like_count=45, created_at=now()-interval '2 days', updated_at=now()-interval '2 days' where region_id='jpc-tokyo' and body='시부야 스크램블은 스타벅스 2층에서 보는 게 제일 잘 보여요.';
update public.city_notes set like_count=37, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-tokyo' and body='신주쿠 골든가이 근처 라멘집들. 자판기로 주문하는 곳이 대부분이에요.';
update public.city_notes set like_count=30, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='jpc-tokyo' and body='센소지는 아침 7시에 가면 사람 거의 없어요. 나카미세 상점가는 9시부터.';
update public.city_notes set like_count=23, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='jpc-tokyo' and body='시모키타자와 빈티지숍 골목. 하루 종일 돌아도 안 지겨워요.';
update public.city_notes set like_count=18, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='jpc-tokyo' and body='츠키지 장외시장 아침 식사. 계란말이랑 참치덮밥 줄 서요.';
update public.city_notes set like_count=10, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='jpc-tokyo' and body='야나카 긴자 상점가 — 옛 도쿄 분위기. 고양이 많아요.';
update public.city_notes set like_count=39, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='jpc-osaka' and body='도톤보리 글리코 간판 앞은 항상 사람 많아요. 밤에 조명 켜지면 예뻐요.';
update public.city_notes set like_count=32, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='jpc-osaka' and body='타코야키는 체인보다 골목 노점이 나아요. 갓 구운 거 뜨거우니 조심.';
update public.city_notes set like_count=22, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='jpc-osaka' and body='오사카성 천수각보다 주변 공원이 좋아요. 벚꽃 시즌엔 인산인해.';
update public.city_notes set like_count=16, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='jpc-osaka' and body='쿠로몬시장에서 해산물 구이. 그 자리에서 먹을 수 있어요.';
update public.city_notes set like_count=8, created_at=now()-interval '27 days', updated_at=now()-interval '27 days' where region_id='jpc-osaka' and body='신세카이 츠텐카쿠 주변 쿠시카츠 골목. 소스 두 번 찍기 금지예요.';
update public.city_notes set like_count=44, created_at=now()-interval '1 days', updated_at=now()-interval '1 days' where region_id='jpc-kyoto' and body='후시미이나리 천 개의 토리이 — 새벽 6시 가면 아무도 없어요. 강추.';
update public.city_notes set like_count=36, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-kyoto' and body='아라시야마 대나무숲은 오전 8시 전에. 늦으면 사진 못 찍어요.';
update public.city_notes set like_count=27, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-kyoto' and body='기온 하나미코지 저녁 산책. 게이코 사진 촬영은 금지라 조심하세요.';
update public.city_notes set like_count=19, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='jpc-kyoto' and body='철학의 길 벚꽃 시즌 최고. 은각사까지 천천히 걸어보세요.';
update public.city_notes set like_count=13, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='jpc-kyoto' and body='니시키시장 먹거리 골목. 두유 도넛이랑 절임 반찬 맛있어요.';
update public.city_notes set like_count=34, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='jpc-fukuoka' and body='나카스 포장마차(야타이)는 저녁 6시부터. 라멘이랑 명란 계란말이.';
update public.city_notes set like_count=27, created_at=now()-interval '10 days', updated_at=now()-interval '10 days' where region_id='jpc-fukuoka' and body='이치란 본점보다 동네 돈코츠 라멘집이 더 진해요. 카에다마 꼭.';
update public.city_notes set like_count=20, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='jpc-fukuoka' and body='다자이후 텐만구는 전철로 30분. 매화 시즌이 예뻐요.';
update public.city_notes set like_count=13, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='jpc-fukuoka' and body='오호리 공원 산책 + 후쿠오카성터. 현지인 조깅 코스예요.';
update public.city_notes set like_count=8, created_at=now()-interval '32 days', updated_at=now()-interval '32 days' where region_id='jpc-fukuoka' and body='모모치 해변 노을. 후쿠오카 타워랑 같이 보면 좋아요.';
update public.city_notes set like_count=33, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='jpc-sapporo' and body='스스키노 징기스칸 — 양고기 냄새 걱정했는데 전혀 안 나요.';
update public.city_notes set like_count=26, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='jpc-sapporo' and body='오타루 운하까지 전철로 40분. 겨울 눈 쌓인 풍경이 그림이에요.';
update public.city_notes set like_count=19, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='jpc-sapporo' and body='삿포로 맥주 박물관 시음 코스. 갓 뽑은 생맥주 맛이 달라요.';
update public.city_notes set like_count=12, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='jpc-sapporo' and body='니조시장 해산물 덮밥. 성게·연어알 올린 거 강추.';
update public.city_notes set like_count=7, created_at=now()-interval '35 days', updated_at=now()-interval '35 days' where region_id='jpc-sapporo' and body='모이와야마 야경 — 일본 3대 야경이라던데 진짜 예뻐요.';
update public.city_notes set like_count=31, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='jpc-naha' and body='마키시 공설시장 1층에서 해산물 사면 2층 식당에서 조리해줘요. 아침에 가야 싱싱해요.';
update public.city_notes set like_count=24, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='jpc-naha' and body='슈리성 성벽 산책로는 무료예요. 복원 공사 과정을 공개하는 것도 볼거리.';
update public.city_notes set like_count=16, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='jpc-naha' and body='츠보야 야치문(도자기) 거리 — 국제거리에서 걸어서 10분인데 분위기가 확 조용해져요.';
update public.city_notes set like_count=10, created_at=now()-interval '28 days', updated_at=now()-interval '28 days' where region_id='jpc-naha' and body='국제거리보다 뒷골목 이자카야가 좋아요. 오키나와 소바 꼭.';
update public.city_notes set like_count=28, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='jpc-nagoya' and body='히츠마부시(장어덮밥) — 세 가지 방식으로 먹는 게 재밌어요.';
update public.city_notes set like_count=18, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='jpc-nagoya' and body='나고야성 천수각은 공사 중일 수 있어요. 혼마루 어전은 볼만해요.';
update public.city_notes set like_count=11, created_at=now()-interval '24 days', updated_at=now()-interval '24 days' where region_id='jpc-nagoya' and body='오스 상점가 — 전자상가랑 빈티지숍 섞여 있어요. 구경거리 많아요.';
update public.city_notes set like_count=6, created_at=now()-interval '34 days', updated_at=now()-interval '34 days' where region_id='jpc-nagoya' and body='미소카츠는 호불호 갈려요. 저는 좋았는데 짜다는 사람도 많아요.';
update public.city_notes set like_count=41, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='thc-bangkok' and body='짜뚜짝 주말시장은 아침 일찍. 오후엔 더워서 못 돌아다녀요.';
update public.city_notes set like_count=34, created_at=now()-interval '7 days', updated_at=now()-interval '7 days' where region_id='thc-bangkok' and body='왓아룬은 강 건너에서 보는 야경이 더 예뻐요. 배 타고 건너세요.';
update public.city_notes set like_count=26, created_at=now()-interval '13 days', updated_at=now()-interval '13 days' where region_id='thc-bangkok' and body='카오산로드는 밤에 가야 제맛. 팟타이 노점 저렴해요.';
update public.city_notes set like_count=20, created_at=now()-interval '18 days', updated_at=now()-interval '18 days' where region_id='thc-bangkok' and body='루프탑 바는 드레스코드 있어요. 반바지·슬리퍼 안 됩니다.';
update public.city_notes set like_count=12, created_at=now()-interval '25 days', updated_at=now()-interval '25 days' where region_id='thc-bangkok' and body='담넌사두억 수상시장은 투어로 가는 게 편해요. 아침 일찍 출발.';
update public.city_notes set like_count=35, created_at=now()-interval '3 days', updated_at=now()-interval '3 days' where region_id='thc-chiangmai' and body='치앙마이 올드시티는 자전거로 도는 게 좋아요. 사원이 골목마다 있어요.';
update public.city_notes set like_count=29, created_at=now()-interval '9 days', updated_at=now()-interval '9 days' where region_id='thc-chiangmai' and body='도이수텝 사원 — 썽태우 타고 올라가요. 해질녘 뷰가 좋아요.';
update public.city_notes set like_count=23, created_at=now()-interval '15 days', updated_at=now()-interval '15 days' where region_id='thc-chiangmai' and body='님만해민 카페거리. 노마드들 많아서 와이파이 잘 돼요.';
update public.city_notes set like_count=17, created_at=now()-interval '20 days', updated_at=now()-interval '20 days' where region_id='thc-chiangmai' and body='일요일 워킹스트리트 야시장. 수공예품 저렴하고 먹거리 많아요.';
update public.city_notes set like_count=11, created_at=now()-interval '26 days', updated_at=now()-interval '26 days' where region_id='thc-chiangmai' and body='카오소이는 치앙마이가 본고장. 로컬 식당이 진짜 맛있어요.';
update public.city_notes set like_count=30, created_at=now()-interval '6 days', updated_at=now()-interval '6 days' where region_id='thc-phuket' and body='빠통은 번잡해요. 조용한 거 원하면 까따·까론 해변으로.';
update public.city_notes set like_count=25, created_at=now()-interval '11 days', updated_at=now()-interval '11 days' where region_id='thc-phuket' and body='피피섬 투어는 스피드보트보다 페리가 덜 흔들려요. 멀미약 챙기세요.';
update public.city_notes set like_count=18, created_at=now()-interval '17 days', updated_at=now()-interval '17 days' where region_id='thc-phuket' and body='푸켓 올드타운 포르투갈풍 건물들. 일요일엔 워킹스트리트 열려요.';
update public.city_notes set like_count=10, created_at=now()-interval '23 days', updated_at=now()-interval '23 days' where region_id='thc-phuket' and body='빅부다 전망대에서 섬 전체가 보여요. 오토바이 렌트하면 편해요.';
update public.city_notes set like_count=27, created_at=now()-interval '5 days', updated_at=now()-interval '5 days' where region_id='thc-pattaya' and body='꼬란섬 당일치기 추천. 방콕에서 가까운데 물은 훨씬 맑아요.';
update public.city_notes set like_count=20, created_at=now()-interval '12 days', updated_at=now()-interval '12 days' where region_id='thc-pattaya' and body='진리의 성전(Sanctuary of Truth) — 통나무 조각이 압도적이에요.';
update public.city_notes set like_count=13, created_at=now()-interval '19 days', updated_at=now()-interval '19 days' where region_id='thc-pattaya' and body='워킹스트리트는 호불호 확실해요. 가족 여행이면 패스.';
update public.city_notes set like_count=7, created_at=now()-interval '29 days', updated_at=now()-interval '29 days' where region_id='thc-pattaya' and body='농눅빌리지 정원 넓어요. 반나절은 잡아야 해요.';
update public.city_notes set like_count=29, created_at=now()-interval '4 days', updated_at=now()-interval '4 days' where region_id='thc-krabi' and body='라일레이 비치는 배로만 갈 수 있어요. 그래서 더 조용해요.';
update public.city_notes set like_count=21, created_at=now()-interval '14 days', updated_at=now()-interval '14 days' where region_id='thc-krabi' and body='에메랄드 풀 + 온천 폭포 코스. 물색이 진짜 에메랄드예요.';
update public.city_notes set like_count=15, created_at=now()-interval '21 days', updated_at=now()-interval '21 days' where region_id='thc-krabi' and body='아오낭에서 4섬 투어. 롱테일보트가 스피드보트보다 운치 있어요.';
update public.city_notes set like_count=9, created_at=now()-interval '30 days', updated_at=now()-interval '30 days' where region_id='thc-krabi' and body='타이거 케이브 사원 계단 1237개… 올라가면 후회 안 해요.';
update public.city_notes set like_count=26, created_at=now()-interval '8 days', updated_at=now()-interval '8 days' where region_id='thc-ayutthaya' and body='왓 마하탓 나무뿌리 불상 머리 — 사진 찍을 때 머리보다 낮게 앉아야 해요.';
update public.city_notes set like_count=18, created_at=now()-interval '16 days', updated_at=now()-interval '16 days' where region_id='thc-ayutthaya' and body='자전거 빌려서 유적 도는 게 최고. 하루면 충분해요.';
update public.city_notes set like_count=11, created_at=now()-interval '22 days', updated_at=now()-interval '22 days' where region_id='thc-ayutthaya' and body='방콕에서 기차로 1시간 반. 3등석도 나쁘지 않아요.';
update public.city_notes set like_count=6, created_at=now()-interval '31 days', updated_at=now()-interval '31 days' where region_id='thc-ayutthaya' and body='일몰 때 왓 차이왓타나람이 붉게 물들어요. 강 건너에서 보세요.';
commit;
